# Generated by Django 5.0.7 on 2024-09-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_alter_instructor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='instructor',
            field=models.CharField(default='instructor', max_length=20),
        ),
    ]
