# Generated by Django 5.0.7 on 2024-09-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_instructor_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
