# Generated by Django 5.0.7 on 2024-08-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_applied_tuitions'),
        ('tuitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionapplication',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
