# Generated by Django 5.0.7 on 2024-09-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='tuition_class',
            field=models.CharField(choices=[('Class_1', 'Class 1'), ('Class_2', 'Class 2'), ('Class_3', 'Class 3'), ('Class_4', 'Class 4'), ('Class_5', 'Class 5'), ('Class_6', 'Class 6'), ('Class_7', 'Class 7'), ('Class_8', 'Class 8'), ('Class_9', 'Class 9'), ('Class_10', 'Class 10'), ('HSC_1', 'HSC 1st Year'), ('HSC_2', 'HSC 2nd Year')], max_length=50),
        ),
    ]
