# Generated by Django 5.0.7 on 2024-07-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuition',
            old_name='tuition_class',
            new_name='class_level',
        ),
    ]
