# Generated by Django 5.0.7 on 2024-07-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0002_rename_tuition_class_tuition_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tuition/images/'),
        ),
    ]
