# Generated by Django 5.0.7 on 2024-07-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0003_tuition_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuition',
            name='class_level',
        ),
        migrations.AddField(
            model_name='tuition',
            name='program',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tuition',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
