# Generated by Django 5.0.7 on 2024-09-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0003_alter_tuition_tuition_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuition',
            old_name='preferred_tutor_gender',
            new_name='instructor_gender',
        ),
    ]
