# Generated by Django 5.0.7 on 2024-09-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0004_rename_preferred_tutor_gender_tuition_instructor_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuition',
            old_name='tutoring_time',
            new_name='tuition_time',
        ),
    ]
