# Generated by Django 5.0.7 on 2024-07-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuitions', '0004_remove_tuition_class_level_tuition_program_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuition',
            old_name='program',
            new_name='level',
        ),
    ]
